name: CI

on:
  push:
    
  pull_request:
    

  workflow_dispatch:

jobs:
    
  prettier: 

      runs-on: ubuntu-latest

      steps: 
        - uses: actions/checkout@v4

        - name: Install Prettier Library
          run: npm install prettier

        - name: Execute prettier
          run: npm run prettier --check src/
